{
  imports = [
    ./kindergarten.nix
    ./datacare.nix
    ./data-accumulator.nix
    ./documentation.nix
    ./lizard.nix
    ./bureaucrat.nix
    ./file_sharing.nix
    ./grafana.nix
    ./map.nix
    ./nginx.nix
    ./postgres.nix
    ./secrets.nix
    ./socket.nix
    ./website.nix
    ./trekkie.nix
    ./chemo.nix
  ];
}
