{
 "title": "Overview",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Systemd Units",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_systemd_unit_state{state=\"active\"})"
    },
    {
     "expr": "sum(node_systemd_unit_state{state=\"failed\"})"
    }
   ]
  },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate({job=\"systemd-journal\"}[1m])"
    }
   ]
  },
  {
   "title": "ASCII-PAY Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-ascii-pay\"}",
     "legendFormat": "ascii-pay"
    }
   ]
  },
  {
   "title": "ASCII-PAY Response Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox-ascii-pay\"}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 29, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\"}"
    }
   ]
  },
  {
   "title": "MemAvailable",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" },
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "Filedescriptors allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    { "expr": "node_filefd_allocated" }
   ]
  },
  {
   "title": "Diskspace Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Network Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"ens3\"}"
    },
    {
     "expr": "node_network_transmit_bytes_total{device=\"ens3\"}"
    }
   ]
  }
 ]
}